### ISSUE TITLE
Needs Documentation Tracking

### ISSUE THREAD

**Issue by TurtIeSocks** [TurtIeSocks/Koji#133]
- [x] Projects
- [x] Escaping special characters for bearer token / secret
- [x] Special characteristics of the `name` property
- [x] nginx file limit size
- [x] nginx default timeout time
- [x] scanner integrations
- [x] scanner default templates
- [x] active vs inactive routes
- [x] docker instructions for trying PRs

**Comment by clburlison** [comment]
- [ ] Cloudflare 100 sec timeout. Best to use use Koji directly without a proxy in front. Still recommend firewall rules.

**Comment by clburlison** [comment]
Marking as resolved.
